# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :build do
    build_app(scheme: "Egendata")
  end

  lane :ios_testflight do

    # Install the required certificates and profile

    setup_travis
    match(
      type: "appstore", 
      readonly: true, 
    )
    

    # Build and deploy to TestFlight
    increment_build_number(xcodeproj: "Egendata.xcodeproj")
    build_app(scheme: "Egendata", export_method: "app-store")
    upload_to_testflight
  end

  lane :beta do
    increment_build_number(xcodeproj: "Egendata.xcodeproj")
    build_app(scheme: "Egendata")

    upload_to_testflight
  end
end
