# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)
xcversion(version: "~> 10")

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :build do
    build_app(scheme: "Egendata")
  end

  lane :certificates do
    match
  end

  lane :beta do
    increment_build_number(xcodeproj: "Egendata.xcodeproj")
    build_app(scheme: "Egendata")


    #match(git_basic_authorization: ENV['GITHUB_CERT_TOKEN'])
    
    upload_to_testflight
  end
end
