# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)


platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build a new alpha version"
  lane :beta do |options|
    tag_prefix = 'android/beta*'
    title = 'Android Beta'
    scheme = 'Egendata'
    groups = 'Beta Team'
    flavor = 'beta'

    # Verify next release
    next unless verify(scheme: scheme, title: title, tag_prefix: tag_prefix)
    # Build ios app

  end

  desc "Verify next release"
  lane :verify do |options|
    # Git status has to be clean
    ensure_git_status_clean
    # if the build is run on local machine
    if !is_ci? then
      clean(scheme: scheme)
    else
      # We don't need to do this on CI because repo is fresh
      echo(message: "#{title} deploy was triggered on CircleCI")
    end

    # Check if there is any change since last version
    is_releaseable = analyze_commits(match: tag_prefix)

    unless is_releaseable
      echo(message: "Skip deploying #{title}. No changes since last one!")
    end

  end

  lane :ci_internal do |version: version|
  
    upload_to_play_store(track: 'internal')
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end

